CREATE TABLE IF NOT EXISTS `products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(40) DEFAULT NULL,
  `price` DOUBLE DEFAULT NULL,
  `category` VARCHAR(40) DEFAULT NULL,
  `pnum` INT(11) DEFAULT NULL,
  `imgurl` VARCHAR(100) DEFAULT NULL,
  `description` VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
